name: PFBarrel
version: '1.0-SNAPSHOT'
main: rimon.pFBarrel.PFBarrelPlugin
api-version: '1.21'
softdepend: [GriefPrevention]
commands:
  pfbarrel:
    description: Main command for PF Barrels
    permission: pfbarrel.admin

  pfsell:
    description: Test command to sell barrel items
    permission: pfbarrel.admin